name: Code Quality & Tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint flake8 bandit pytest pytest-cov

    - name: Run pylint
      run: |
        pylint --output-format=text restaurant_model_training/ || echo "Pylint issues found"
    
    - name: Run flake8
      run: flake8 restaurant_model_training/ --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Run bandit
      run: bandit -r restaurant_model_training/ -c bandit.yaml -f json -o bandit-results.json || echo "Bandit issues found"
    
    - name: Run tests with coverage
      run: |
        pytest tests/ --cov=restaurant_model_training --cov-report=xml
        
    - name: Upload coverage to README
      run: |
        echo "## Test Coverage" >> $GITHUB_STEP_SUMMARY
        cat coverage.xml | grep -o 'line-rate="[0-9.]*"' | head -1 | cut -d'"' -f2 | awk '{print "Coverage: " $1*100 "%"}' >> $GITHUB_STEP_SUMMARY